# Terraform "random" Provider
#
# Description:
# The "random" provider allows the use of randomness within Terraform configurations. This is a
# logical provider, which means that it works entirely within Terraform's logic, and doesn't interact
# with any other services.
#
# The random hashed random ID generated by this resource is, for example, used as the CloudFront
# token (HTTP header "CloudFront-Token"). The token can be used in the load balancer to restrict access.
# https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/restrict-access-to-load-balancer.html
#
# AWS Documentation:
# n/a
#
# Terrafom Documentation:
# https://registry.terraform.io/providers/hashicorp/random/latest/docs
# https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/id

resource "random_id" "hash" {
    byte_length = 8
}
